<?php

namespace Digueloulou12\Spawner\Items;

use Digueloulou12\Spawner\Blocks\SpawnerBlock;
use Digueloulou12\Spawner\Entities\MobEntity;
use Digueloulou12\Spawner\Spawner;
use pocketmine\block\Block;
use pocketmine\item\ItemUseResult;
use pocketmine\item\SpawnEgg;
use pocketmine\math\Vector3;
use pocketmine\player\Player;
use pocketmine\world\World;

class SpawnEggItem extends SpawnEgg
{
    protected function createEntity(World $world, Vector3 $pos, float $yaw, float $pitch): MobEntity
    {
        return Spawner::getInstance()->getSpawnEntity($world, $pos, $yaw, $pitch, $this->getMeta());
    }

    public function onInteractBlock(Player $player, Block $blockReplace, Block $blockClicked, int $face, Vector3 $clickVector): ItemUseResult
    {
        if ($blockClicked instanceof SpawnerBlock) {
            return ItemUseResult::NONE();
        }
        return parent::onInteractBlock($player, $blockReplace, $blockClicked, $face, $clickVector); // TODO: Change the autogenerated stub
    }
}