---
gui.title: "§c§lKit"

achlis.slot: "40"
achlis.id: "267"
achlis.name: "§r§cKit Achlis"
achlis.perm: "achlis.kit"
no.perm.achlis: "Vous n'avez pas la permission de prendre ce kit !"
achlis.item:
  - "310:0:1:default:protection:1"
  - "311:0:1:default:protection:1"
  - "312:0:1:default:protection:1"
  - "313:0:1:default:protection:1"
  - "276:0:1:default:sharpness:1"
  - "368:0:6"
  - "353:0:4"
  - "438:22:64"
achlis.message: "Vous venez de récupérer le kit §cAchlis§f !"

baku.slot: "31"
baku.id: "283"
baku.name: "§r§cKit Baku"
baku.perm: "baku.kit"
no.perm.baku: "Vous n'avez pas la permission de prendre ce kit !"
baku.item:
  - "310:0:1:default:protection:2"
  - "311:0:1:default:protection:2"
  - "312:0:1:default:protection:2"
  - "313:0:1:default:protection:2"
  - "276:0:1:default:sharpness:2"
  - "368:0:9"
  - "353:0:6"
  - "438:22:64"
baku.message: "Vous venez de récupérer le kit §cBaku§f !"

cocatrix.slot: "21"
cocatrix.id: "352"
cocatrix.name: "§r§cKit Cocatrix"
cocatrix.perm: "cocatrix.kit"
no.perm.cocatrix: "Vous n'avez pas la permission de prendre ce kit !"
cocatrix.item:
  - "314:0:1:default:protection:2:unbreaking:2"
  - "311:0:1"
  - "312:0:1"
  - "317:0:1:default:protection:2:unbreaking:2"
  - "368:0:12"
  - "353:0:9"
  - "438:22:64"
cocatrix.message: "Vous venez de récupérer le kit §cCocatrix§f !"

diti.slot: "23"
diti.id: "369"
diti.name: "§r§cKit Diti"
diti.perm: "diti.kit"
no.perm.diti: "Vous n'avez pas la permission de prendre ce kit !"
diti.item:
  - "314:0:1:default:protection:2:unbreaking:3"
  - "311:0:1:default:protection:1:unbreaking:3"
  - "312:0:1:default:protection:1:unbreaking:3"
  - "317:0:1:default:protection:2:unbreaking:3"
  - "368:0:6"
  - "353:0:4"
  - "438:22:64"
diti.message: "Vous venez de récupérer le kit §cDiti§f !"

builder.slot: "13"
builder.id: "257"
builder.name: "§r§cKit Builder"
builder.perm: "builder.kit"
no.perm.builder: "Vous n'avez pas la permission de prendre ce kit !"
builder.item:
  - "1:0:64"
  - "30:0:128"
  - "96:0:128"
  - "278:0:1:default:efficiency:5"
  - "279:0:1:default:efficiency:5"
  - "277:0:1:default:efficiency:5"
  - "1:0:64"
  - "2:0:128"
  - "17:0:64"
  - "76:0:64"
  - "152:0:64"
  - "12:0:64"
  - "20:0:64"
  - "1:0:128"
  - "2:0:128"
  - "17:0:64"
  - "33:1:64"
  - "29:1:64"
  - "12:0:64"
  - "20:0:64"
  - "1:0:128"
  - "2:0:128"
  - "17:0:64"
  - "356:0:64"
  - "404:0:64"
  - "12:0:64"
  - "20:0:64"
  - "1:0:128"
builder.message: "Vous venez de récupérer le kit §cBuilder§f !"
...